services:
  sql_server:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server
    hostname: sql_server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd"
    restart: unless-stopped